SELECT *
FROM  SETOPERATORNUMBERDEMO1
UNION ALL
SELECT *
FROM  SETOPERATORNUMBERDEMO2

SELECT COLORNAME, SORTORDER 
FROM COLORTABLE1
UNION ALL
SELECT COLORNAME, TRY_CAST (SORTORDER AS INT)
FROM COLORTABLE2