SELECT *
FROM NUMBERS
ORDER BY NumericValue

SELECT SUM(NUMERICVALUE) AS TOTALOFFIELDVALUES 
FROM NUMBERS

SELECT COUNT(NUMERICVALUE) AS RECORDCOUNT 
FROM NUMBERS

SELECT AVG(NUMERICVALUE) 
FROM NUMBERS

SELECT AVG(CAST(NUMERICVALUE AS DECIMAL(5,2))) AS AVERAGE
FROM NUMBERS

SELECT DISTINCT NUMERICVALUE
FROM NUMBERS
ORDER BY NumericValue

SELECT SUM(DISTINCT NUMERICVALUE)
FROM NUMBERS

SELECT COUNT(DISTINCT NUMERICVALUE) 
FROM NUMBERS

SELECT AVG(DISTINCT NUMERICVALUE) 
FROM NUMBERS

