SELECT *
FROM NUMBERS
ORDER BY NUMERICVALUE

SELECT MIN(NUMERICVALUE) AS MINNUMBER 
FROM NUMBERS

SELECT MAX(NUMERICVALUE) AS MAXNUMBER 
FROM NUMBERS

SELECT *
FROM SALES

SELECT CONVERT (varchar, MAX (ORD_DATE), 101) AS MOSTRECENTSALEDATE,
       CONVERT (varchar, MIN (ORD_DATE),101) AS FIRSTSALEDATE,
       SUM(QTY) AS TOTALBOOKSSOLDTODATE, 
	   COUNT (*) AS TOTALNUMBEROFSALES, 
	   AVG(QTY) AVGNUMBERORDERPERSALE
FROM SALES;

SELECT *
FROM SALES 
ORDER BY ORD_DATE 