SELECT
PA. PRODUCT,
SUM(SALES_QTY) AS SALES_QTY
FROM F_Sales F
JOIN D_Product_Attributes1 PA
ON F.Product_code=PA.product_code
WHERE PA.PRODUCT='DRESS'
GROUP BY PA.PRODUCT
ORDER BY 2 DESC

SELECT
PA. SIZE,
PA.SEASON,
PA.PRODUCT_TYPE,
SUM(SALES_QTY) AS SALES_QTY
FROM F_Sales F
JOIN D_Product_Attributes1 PA
ON F.Product_code=PA.product_code
WHERE PA.PRODUCT='DRESS'
GROUP BY PA.SIZE, PA.SEASON, PA.PRODUCT_TYPE
ORDER BY 1,2,4 DESC