SELECT
    PRODUCT_CODE,
	product,
	PRODUCT_CATEGORY,
	CASE WHEN PRODUCT = 'DRESS' THEN 'FEMALE'
	ELSE 'UNISEX' END AS pRODUCT_GENDER
	FROM D_PRODUCT_CATEGORY

	SELECT
    PRODUCT_CODE,
	product,
	PRODUCT_CATEGORY,
	CASE WHEN PRODUCT = 'DRESS' THEN 'FEMALE'
	WHEN PRODUCT_CATEGORY IN('ACCESORIES', 'BOTTOMS', 'OVERWEAR') AND LEFT(PRODUCT_CODE,1)=1 THEN 'MALE'
	WHEN PRODUCT_CATEGORY IN('ACCESORIES', 'BOTTOMS', 'OVERWEAR') AND LEFT(PRODUCT_CODE,1)=9 THEN 'FEMALE'
	WHEN PRODUCT_CATEGORY = 'TOPS' AND (LEFT(PRODUCT_CODE,1)=9 OR PRODUCT='BLOUSE')            THEN 'FEMALE'
	WHEN PRODUCT_CATEGORY = 'TOPS'                                                             THEN 'MALE'
	ELSE 'UNISEX' END AS pRODUCT_GENDER
	FROM D_PRODUCT_CATEGORY
	WHERE CASE WHEN PRODUCT = 'DRESS' THEN 'FEMALE'
	WHEN PRODUCT_CATEGORY IN('ACCESORIES', 'BOTTOMS', 'OVERWEAR') AND LEFT(PRODUCT_CODE,1)=1 THEN 'MALE'
	WHEN PRODUCT_CATEGORY IN('ACCESORIES', 'BOTTOMS', 'OVERWEAR') AND LEFT(PRODUCT_CODE,1)=9 THEN 'FEMALE'
	WHEN PRODUCT_CATEGORY = 'TOPS' AND (LEFT(PRODUCT_CODE,1)=9 OR PRODUCT='BLOUSE')            THEN 'FEMALE'
	WHEN PRODUCT_CATEGORY = 'TOPS'                                                             THEN 'MALE'
	ELSE 'UNISEX' END='UNISEX'