SELECT SALES_YEAR, 
       PRODUCT, 
	   PRODUCT_TYPE,
	   SUM(Total_Sales_Qty) AS ANNUAL_SALES,
	   FIRST_VALUE (SUM (TOTAL_SALES_QTY)) OVER (ORDER BY SUM(TOTAL_SALES_QTY) RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS FIRST_VALUE,
	   LAST_VALUE (SUM (TOTAL_SALES_QTY)) OVER (ORDER BY SUM(TOTAL_SALES_QTY) RANGE BETWEEN CURRENT ROW AND UNBOUNDED FOLLOWING) AS LAST_VALUE
FROM A_SALES_BY_YEAR 
GROUP BY SALES_YEAR, PRODUCT, PRODUCT_TYPE