SELECT PRODUCT, SALES_DATE, SUM(SALES_VALUE)
FROM Sales_Star
GROUP BY PRODUCT, SALES_DATE

SELECT O.SALES_DATE AS LAST_SALES_DATE, PRODUCT
FROM Sales_Star O
WHERE O.Sales_Date =
  (SELECT MAX(I.SALES_DATE) FROM SALES_STAR I
  WHERE O.PRODUCT=I.PRODUCT)
GROUP BY O.PRODUCT, O.SALES_DATE
ORDER BY SALES_DATE DESC

SELECT P.CUSTOMER_CODE 
FROM
(
	  SELECT CUSTOMER_CODE,
	  CAST(PERCENT_RANK() OVER(ORDER BY SUM (SALES_VALUE)) AS DECIMAL(4,2)) AS PERCENTILE
	  FROM SALES_STAR
	  GROUP BY CUSTOMER_CODE
) AS P
WHERE P.PERCENTILE=1;
