SELECT SALES_YEAR, PRODUCT, 
	   SUM(Total_Sales_Qty) AS ANNUAL_SALES,
	   FORMAT (PERCENT_RANK() OVER(ORDER BY SUM(TOTAL_SALES_QTY) ASC),'P') AS PERSENT_RANK_ALL,
DENSE_RANK () OVER(ORDER BY SUM(TOTAL_SALES_QTY) DESC) AS RANK
FROM A_SALES_BY_YEAR WHERE Sales_Year=2018
GROUP BY SALES_YEAR, PRODUCT
ORDER BY 4 DESC