SELECT SALES_YEAR, 
       PRODUCT, 
	   SUM(Total_Sales_Qty) AS ANNUAL_SALES,
NTILE(4) OVER(PARTITION BY SALES_YEAR ORDER BY SUM(TOTAL_SALES_QTY) DESC) AS NTILE
FROM A_SALES_BY_YEAR
GROUP BY SALES_YEAR, PRODUCT