select 
STUFF(PRODUCT_DESCRIPTION,
CHARINDEX(' ',PRODUCT_DESCRIPTION),
1,'&')
FROM D_Product

select REPLACE(
STUFF(PRODUCT_DESCRIPTION,
CHARINDEX(' ',PRODUCT_DESCRIPTION),
1,'&'),
' ','-')
FROM D_Product

CREATE VIEW V_PRODUCT_BASE
AS
select PRODUCT_CODE,
REPLACE(
REPLACE(
REPLACE(
STUFF(PRODUCT_DESCRIPTION,
CHARINDEX(' ',PRODUCT_DESCRIPTION),1,'&'),
' ','-'),
'LIGHT-BLUE','LIGHTBLUE'),
'LIGHT-GREEN','LIGHTGREEN')
AS CLEAN_PRODUCT_DESCRIPTION
FROM D_Product

SELECT *
FROM V_PRODUCT_BASE